### ISSUE TITLE
Create "Current Project" Page

### ISSUE THREAD

**Issue by reconwhispers** [KidSysco/dig-a-hash-web#13]
Add place to put "Degen Shindig Present"
Add place for incoming logo
Add place for small descript- "Degen Carnival with P2E NFT mini games"
Add link to twitter and discord

Add "Current Game" Section
Add place for logo for current game
Add place for  small descript

**Comment by boristotle** [comment]
https://github.com/KidSysco/dig-a-hash-web/pull/16
