### ISSUE TITLE
Update Roadmap and Repost

### ISSUE THREAD

**Issue by reconwhispers** [KidSysco/dig-a-hash-web#19]
0- Can you add version 2 or Roadmap v 2.0 or something like that to signal an update?
1- remove all socials and branding from bottom right corner of roadmap graphic: digahashholdings and twitter handles
2-UPDATE P2- 
-Build NFTy Stay brand
-Establish Collaborations
-1st Monetization Project
3- UPDATE P3-
-Back 1st NFT Project Launch
-Build out infrastructure
4- UPDATE P4-
-Update Roadmap to v3.0
![image](https://user-images.githubusercontent.com/97454558/160838189-8924e50f-4463-4b8d-b8f9-e927a1395023.png)

**Comment by KidSysco** [comment]
Updated here... https://dig-a-hash-3sakmee0e-kidsysco.vercel.app/
