### ISSUE TITLE
Change Legacy LAO to Coming Soon

### ISSUE THREAD

**Issue by reconwhispers** [KidSysco/dig-a-hash-web#3]
Continue the theme of "dig-a" stuff I like that for branding 

Change
to 
![coming soon](https://user-images.githubusercontent.com/97454558/148791544-0b076e5c-b317-45f6-90c6-35672e9e9fc2.png)

Dig-A-First Project
Coming Soon

And can we add a coming soon image that fits the site
I want to strategically roll out the name and logo
And then change top menu to "project" until we update to Legacy LAO
Thoughts?

**Comment by reconwhispers** [comment]
![coming soon](https://user-images.githubusercontent.com/97454558/148790523-b1357657-753e-4e1b-8508-a1b8ba840ba0.png)

**Comment by reconwhispers** [comment]
something to that effect

**Comment by reconwhispers** [comment]
And then change top menu to "project" until we update to Legacy LAO

**Comment by boristotle** [comment]
idk i think from a users standpoint it's good as is so they know exactly what is upcoming.  i think specifics and clarity are always better than vagueness if you can do it.

**Comment by boristotle** [comment]
replaced legacy lao with dig a 1st project, coming soon: https://github.com/KidSysco/dig-a-hash-web/pull/10
